# ТЗ на позицию Data-analyst

Для выполнения данного задания предлагается использовать следующую структуру данных:

*	Таблица "users" с полями: id, name, email, created_at

*	Таблица "orders" с полями: id, user_id, total_price, created_at

*	Таблица "order_items" с полями: id, order_id, product_name, price, quantity

В ответе пришлите имя и версию используемой бд, дамп структуры базы, а также запросы для заполнения тестовыми данными, в работе строк должно быть не менее 1 млн в каждой таблице.
Ответ должен представлять из себя SQL запрос с пояснением. По желанию можете дополнить ваш ответ плохим вариантом запроса также с объяснением.

Запросы:

1.	Найти общее количество заказов каждого пользователя, который сделал более 10 заказов.

2.	Найти средний размер заказа для каждого пользователя за последний месяц.

3.	Найти средний размер заказа за каждый месяц в текущем году и сравнить его с средним размером заказа за соответствующий месяц в прошлом году.

4.	Найти 10 пользователей, у которых наибольшее количество заказов за последний год, и для каждого из них найти средний размер заказа за последний месяц.

_____________________________________________________________________

### 1. Сгенерируем тестовые данные


Тетрадка с описанием процесса создания тестовых данных [**здесь**](https://drive.google.com/file/d/1fCf3Ku97ZPdFZz0vTmWeAblhFmyMR1uW/view?usp=share_link)


_____________________________________________________________________________

### 2. Зальём полученные данные в БД

Имя и версия используемой бд: <span style="color:red"> **PostgreSQL 15.2**</span> 

Дамп структуры базы данных [**здесь**](https://drive.google.com/file/d/1qo_mWPCkZ47r5dbxVqYD7wENwFFMDafK/view?usp=share_link)

##### Шаг 1. С помощью визуального редактора для PostgresSQL программы PgAdmin создадим БД "happy_games".

##### Шаг 2. Создадим необходимые таблицы с соответствующими взаимосвязями

In [1]:
# 1. Импортируем необходимые библиотеки.
import pandas as pd
import numpy as np
import psycopg2 as ps
from sqlalchemy import create_engine

In [2]:
# 2. Создим соединение с базой данных PostgreSQL.
conn = ps.connect(database ="happy_games",
                  user = "postgres", 
                  password = "maz505+5", 
                  host = "localhost",
                  port = "5432") 

# 3. Создадим курсор - это специальный объект который делает запросы и получает их результаты.
cur = conn.cursor()

In [3]:
# 4. Создадим нашу первую таблицу "users"  со следующей структурой данных:
#      id: SERIAL PRIMARY KEY
#      name: VARCHAR(50) 
#      email: VARCHAR(50)
#      created_at: DATE
cur.execute("""CREATE TABLE users (
               id SERIAL PRIMARY KEY, 
               name VARCHAR(50), 
               email VARCHAR(50), 
               created_at DATE)
            """)

In [4]:
# 5. Аналогично создадим  таблицу "orders" со следующей структурой данных:
#      id: SERIAL PRIMARY KEY
#      user_id: INTEGER NOT NULL
#      total_price: NUMERIC(10, 2)
#      created_at: DATE
#      FOREIGN KEY (user_id) REFERENCES users (id)

cur.execute("""CREATE TABLE orders (
               id SERIAL PRIMARY KEY, 
               user_id INTEGER NOT NULL, 
               total_price NUMERIC(10, 2), 
               created_at DATE, 
               FOREIGN KEY (user_id) REFERENCES users(id))
            """)

In [5]:
# 6. Создадим таблицу order_items со следующей структурой данных:
#       id: SERIAL PRIMARY KEY
#       order_id: INTEGER NOT NULL
#       product_name: VARCHAR(50) 
#       price: NUMERIC(10, 2) 
#       quantity: INTEGER 
#       FOREIGN KEY (order_id) REFERENCES orders (id)
cur.execute("""CREATE TABLE order_items (
               id SERIAL PRIMARY KEY, 
               order_id INTEGER NOT NULL, 
               product_name VARCHAR(50), 
               price NUMERIC(10, 2), 
               quantity INTEGER, 
               FOREIGN KEY (order_id) REFERENCES orders (id))
            """)

In [6]:
# 7. Cохраним изменения.
conn.commit()

In [7]:
# 8. Закрываем курсор и соединение с базой данных
cur.close()
conn.close()

#### Шаг 3. Приступим к заполнению таблиц

In [8]:
# 1. Создадим новое подключение к БД через sqlalchemy
conn = create_engine('postgresql+psycopg2://postgres:maz505+5@localhost:5432/happy_games')

In [9]:
# 2. Метод для ускорения процесса записи данных (https://stackoverflow.com/a/55495065/4527289)

import csv
from io import StringIO

def psql_insert_copy(table, conn, keys, data_iter):
    # gets a DBAPI connection that can provide a cursor
    dbapi_conn = conn.connection
    with dbapi_conn.cursor() as cur:
        s_buf = StringIO()
        writer = csv.writer(s_buf)
        writer.writerows(data_iter)
        s_buf.seek(0)

        columns = ', '.join('"{}"'.format(k) for k in keys)
        if table.schema:
            table_name = '{}.{}'.format(table.schema, table.name)
        else:
            table_name = table.name

        sql = 'COPY {} ({}) FROM STDIN WITH CSV'.format(
            table_name, columns)
        cur.copy_expert(sql=sql, file=s_buf)

In [10]:
# 3. Считываем ранее сгенерированные данные, а именно users.csv.
#    Так как колонка 'id' у нас будет являться первичным ключом, и мы при создании таблицы на предыдущем шаге 
#    устанавили параметры для неё SERIAL PRIMARY KEY, избавимся от колонок 'id' в наших датафреймах.
df_users = pd.read_csv('users.csv', parse_dates=['created_at'])
df_users = df_users[['name', 'email', 'created_at']]
df_users.head(2)

           name                     email created_at
0  Ebony Peters     krobinson@example.net 2022-01-01
1  Andrew Davis  robertrivera@example.com 2022-01-01

In [11]:
# 4. Используем метод to_sql() у объекта DataFrame для вставки данных в таблицу базы данных.
df_users.to_sql('users', conn, if_exists='append', index=False, method=psql_insert_copy)

In [12]:
# Проверим, сделав первый запрос.
# Чтобы меньше печатать завернем функцию  pd.read_sql() в функцию select.
def select(sql):
  return pd.read_sql(sql,conn)

In [13]:
sql = '''SELECT * FROM users LIMIT 10'''

In [14]:
select(sql)

   id                name                        email  created_at
0   1        Ebony Peters        krobinson@example.net  2022-01-01
1   2        Andrew Davis     robertrivera@example.com  2022-01-01
2   3         Chad Conley       timothylee@example.com  2022-01-01
3   4        Sheila Scott     colliersarah@example.com  2022-01-01
4   5      Logan Stephens  williamharrison@example.net  2022-01-01
5   6        Mark Salazar          jimmy02@example.com  2022-01-01
6   7    Holly Schmidt MD      jeffreycole@example.com  2022-01-01
7   8  Elizabeth Thompson      alexander09@example.org  2022-01-01
8   9       Cynthia Sharp       davisrobin@example.org  2022-01-01
9  10    Kristin Mitchell       mccoyperry@example.org  2022-01-01

In [15]:
# 5. Считываем ранее сгенерированный файл orders.csv.
df_orders = pd.read_csv('orders.csv', parse_dates=['created_at'])
df_orders = df_orders[['user_id', 'created_at', 'total_price']]
df_orders.head(2)

   user_id created_at  total_price
0     1024 2022-02-09       619280
1      539 2022-02-09       143450

In [16]:
# 6. Используем метод to_sql() у объекта DataFrame для вставки данных в таблицу базы данных.
df_orders.to_sql('orders', conn, if_exists='append', index=False, method=psql_insert_copy)

In [17]:
# Проверим, сделав запрос.
sql = '''SELECT * FROM orders LIMIT 10'''

In [18]:
select(sql)

   id  user_id  total_price  created_at
0   1     1024     619280.0  2022-02-09
1   2      539     143450.0  2022-02-09
2   3      896     911150.0  2022-02-09
3   4      250     508350.0  2022-02-09
4   5      409     829370.0  2022-02-09
5   6     2031     527860.0  2022-02-09
6   7      636     704390.0  2022-02-09
7   8     1676     407870.0  2022-02-09
8   9     1264      29200.0  2022-02-09
9  10      599     938280.0  2022-02-09

In [19]:
# 7. По аналогии с предыдущими шагами.
df_order_items = pd.read_csv('order_items.csv')
df_order_items = df_order_items[['order_id', 'product_name', 'price', 'quantity']]
df_order_items.head(2)

   order_id           product_name      price  quantity
0   2673627  Prod.№: NPuG-25470804  695120.00         1
1   2771900  Prod.№: QjBH-91429237   52077.69        13

In [20]:
df_order_items.to_sql('order_items', conn, if_exists='append', index=False, method=psql_insert_copy)

In [22]:
sql = '''SELECT * FROM order_items LIMIT 10'''

In [23]:
select(sql)

   id  order_id           product_name      price  quantity
0   1   2673627  Prod.№: NPuG-25470804  695120.00         1
1   2   2771900  Prod.№: QjBH-91429237   52077.69        13
2   3   1653831  Prod.№: VrQh-10306637   62345.56         9
3   4    217249  Prod.№: eOtB-50617539   56884.17        12
4   5   1802478  Prod.№: TOJe-97596301  199376.00         5
5   6    689489  Prod.№: bTyM-12937895   81891.25         8
6   7   3625966  Prod.№: HVpg-84929674   28202.22         9
7   8    532274  Prod.№: Iakp-58025312   10484.67        15
8   9   3561966  Prod.№: IZvf-45126819  147320.00         1
9  10     84230  Prod.№: Spxz-93722231  304123.33         3

__________________________________________________


### 3. Приступим к составлению запросов, для ответов на поставленные вопросы

1. Найти общее количество заказов каждого пользователя, который сделал более 10 заказов.
   
   Таблица "orders" с полями: id, user_id, total_price, created_at

In [50]:
# 1ый вариант (на мой взгляд,наиболее оптимальный)

sql = '''
WITH cte AS (SELECT o.user_id AS user_id
               FROM orders o                
              GROUP BY 1
             HAVING count(distinct o.id) > 10
             )
             
  SELECT o.user_id, u.name, u.email,
         COUNT(DISTINCT o.id)  AS cnt_orders       
    FROM orders o JOIN cte 
         ON o.user_id = cte.user_id
                  JOIN users u
         ON o.user_id = u.id
   GROUP BY 1, 2, 3
       '''
# Этот запрос использует CTE для выбора всех пользователей, у которых есть более 10 заказов. 
# Затем, запрос присоединяет этих пользователей к таблице orders с помощью INNER JOIN, 
# тем самым отбирая только нужные нам данные.
# Если есть необходимость, то ещё джойним таблицу users и получаем подробную информацию по юзерам.
# Так же эту задачу можно решить используя подзапрос вместо CTE,
# однако, вариант с использованием CTE, на мой взгляд, является наиболее оптимальным.

In [51]:
select(sql)

       user_id             name                          email  cnt_orders
0           23     Chad Griffin          xrichards@example.com          16
1           64      Debra Perez        katherine10@example.net          11
2          104  Zachary Johnson         meganprice@example.com          11
3          148       April Cruz  richardsoncynthia@example.org          13
4          175        Rick Ford         judyrivera@example.net          11
...        ...              ...                            ...         ...
13658   999776       Lisa Garza       smithallison@example.org          11
13659   999840     Jaime Hughes           edward79@example.net          11
13660   999890    Rodney Barnes       davisjeffrey@example.org          12
13661   999952    Matthew Black   terrychristopher@example.net          11
13662   999964     Paula Carter         brookedunn@example.net          12

[13663 rows x 4 columns]

In [52]:
# 2ой вариант 

sql = '''
     SELECT o.user_id, u.name, u.email,
            COUNT(DISTINCT o.id)  AS cnt_orders       
       FROM orders o
            JOIN                                      
                 (SELECT o.user_id AS user_id
                    FROM orders o                
                   GROUP BY 1
                  HAVING count(distinct o.id) > 10
                  ) AS q 
              ON o.user_id = q.user_id
            JOIN users u
              ON o.user_id = u.id
     GROUP BY 1, 2, 3
       '''
# Аналогичен первому, однако использование CTE для больших данных эффективнее.

In [53]:
select(sql)

       user_id             name                          email  cnt_orders
0           23     Chad Griffin          xrichards@example.com          16
1           64      Debra Perez        katherine10@example.net          11
2          104  Zachary Johnson         meganprice@example.com          11
3          148       April Cruz  richardsoncynthia@example.org          13
4          175        Rick Ford         judyrivera@example.net          11
...        ...              ...                            ...         ...
13658   999776       Lisa Garza       smithallison@example.org          11
13659   999840     Jaime Hughes           edward79@example.net          11
13660   999890    Rodney Barnes       davisjeffrey@example.org          12
13661   999952    Matthew Black   terrychristopher@example.net          11
13662   999964     Paula Carter         brookedunn@example.net          12

[13663 rows x 4 columns]

In [54]:
# 3ий вариант 
sql = '''

SELECT q.user_id, u.name, u.email,
       q.total_cnt_orders
  FROM
       (SELECT o.user_id AS user_id,
               o.id AS order_id,
               COUNT(o.id) OVER (PARTITION BY o.user_id) AS total_cnt_orders
          FROM orders o
        ) AS q
        JOIN users u
              ON q.user_id = u.id
 WHERE q.total_cnt_orders > 10
 GROUP BY 1, 2, 3, 4
'''
# 1)  В подзапросе с помощью оконной функции для каждого юзера считаем общее количество заказов.
# 2)  Джойним таблицу users
# 2)  Внешним запросом фильтруем пользователей у которых больше 10 заказов и с целью избавления от дубликатов группируем.

In [55]:
select(sql)

,user_id,name,email,total_cnt_orders
0,23,Chad Griffin,xrichards@example.com,16
1,64,Debra Perez,katherine10@example.net,11
2,104,Zachary Johnson,meganprice@example.com,11
3,148,April Cruz,richardsoncynthia@example.org,13
4,175,Rick Ford,judyrivera@example.net,11
...,...,...,...,...
13658,999776,Lisa Garza,smithallison@example.org,11
13659,999840,Jaime Hughes,edward79@example.net,11
13660,999890,Rodney Barnes,davisjeffrey@example.org,12
13661,999952,Matthew Black,terrychristopher@example.net,11
13662,999964,Paula Carter,brookedunn@example.net,12

_______________________________________

2. Найти средний размер заказа для каждого пользователя за последний месяц.

In [56]:
# 1ый вариант:
sql = ''' 

SELECT user_id,
       ROUND(AVG(total_price),2) AS avg_total_price
  FROM orders
 WHERE to_char(created_at, 'MM-YYYY') = '04-2023' 
 GROUP BY 1
       
       '''

In [57]:
select(sql)

       user_id  avg_total_price
0       898508        428946.67
1       904129        519283.33
2       896736        557682.22
3       913262        653667.78
4       900716        438066.67
...        ...              ...
64154   922766        612645.00
64155   951142        400980.00
64156   936051        620022.50
64157   924414        456056.67
64158   936961        353147.50

[64159 rows x 2 columns]

In [58]:
# 2ой вариант:
sql = ''' 

SELECT DISTINCT user_id,
       AVG(orders.total_price) OVER (PARTITION BY user_id) AS avg_total_price
  FROM orders
 WHERE to_char(created_at, 'MM-YYYY') = '04-2023'

      '''

In [59]:
select(sql)

       user_id  avg_total_price
0       954076    593836.000000
1       936945    608665.000000
2       913574    516825.714286
3       945985    460470.000000
4       937753    353352.000000
...        ...              ...
64154   898076    703213.333333
64155   911977    595560.000000
64156   904421    724965.000000
64157   942852    556725.714286
64158   928198    417230.000000

[64159 rows x 2 columns]

In [60]:
# Первый вариант выполняет группировку по пользователям, а затем вычисляет среднее значение для каждой группы, тогда как второй
# вариант вычисляет среднее значение для каждой строки, используя оконную функцию. 
# В результате первый вариант требует меньше операций с данными и, предположительно, должен работать быстрее.

3. Найти средний размер заказа за каждый месяц в текущем году и сравнить его с средним размером заказа за соответствующий месяц в прошлом году.

In [61]:
# На первом этапе решения данной задачи вычленим из даты 'created_at' год и месяц, 
# затем данные отсортируем сначала по году, затем по месяцу.

sql = ''' 

SELECT q.year, q.month, q.avg_money
FROM (
        SELECT 
                to_char(created_at, 'YYYY') AS year,
                to_char(created_at, 'MM') AS month,
                ROUND(AVG(total_price), 2) AS avg_money
        FROM orders
        GROUP BY 1, 2
        ORDER BY 2, 1 ASC
    ) q
     '''

In [62]:
# В результате получим таблицу следующего вида:
select(sql)

    year month  avg_money
0   2023    01  499513.75
1   2022    02  502147.60
2   2023    02  500066.33
3   2022    03  500262.76
4   2023    03  499642.36
5   2022    04  500495.49
6   2023    04  500617.86
7   2022    05  500384.95
8   2023    05  500299.89
9   2022    06  501155.39
10  2022    07  500008.90
11  2022    08  499344.20
12  2022    09  500534.61
13  2022    10  499187.03
14  2022    11  499771.87
15  2022    12  499911.98

In [63]:
# 1. Доработаем предыдущий запрос, добавив оконную функцию смещения LAG.
# 2. Дабы избежать подзапросов поместим наш запрос в представление.
# 3. Отберём строки с текущим годом.
# 4. Рассчитаем разницу (абсолютный прирост / темп роста )


sql = ''' 

WITH cte AS (
             SELECT 
                to_char(created_at, 'YYYY') AS year,
                to_char(created_at, 'MM') AS month,
                ROUND(AVG(total_price), 2) AS avg_money_2023,
                LAG(ROUND(AVG(total_price), 2)) OVER(PARTITION BY to_char(created_at, 'MM') ORDER BY to_char(created_at, 'YYYY')) AS last_year_avg_money
             FROM orders
             GROUP BY 1, 2
             ORDER BY 2, 1 ASC
           )

SELECT *, 
       (avg_money_2023 - last_year_avg_money) AS absolute_increase,
       (((avg_money_2023 / last_year_avg_money) - 1) * 100) AS growth_rate_in_percentage
  FROM cte
 WHERE cte.year = '2023'
'''

In [64]:
select(sql)

,year,month,avg_money_2023,last_year_avg_money,absolute_increase,growth_rate_in_percentage
0,2023,01,499513.75,NaN,NaN,NaN
1,2023,02,500066.33,502147.60,-2081.27,-0.414474
2,2023,03,499642.36,500262.76,-620.40,-0.124015
3,2023,04,500617.86,500495.49,122.37,0.024450
4,2023,05,500299.89,500384.95,-85.06,-0.016999

Данную задачу можно решить без применения оконных функций, с помощью джойнов по месяцу двух подзапросов с отобранными по году данными, но это совсем не тот подход.

4. Найти 10 пользователей, у которых наибольшее количество заказов за последний год, и для каждого из них найти средний размер заказа за последний месяц.

In [65]:
# 1 шаг. Найдём 10 юзеров с наибольшим количеством заказов за последний год

sql = ''' 
SELECT 
      user_id,
      COUNT(DISTINCT id) AS cnt_orders
FROM orders
WHERE to_char(created_at, 'YYYY') = '2023'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
            '''

In [66]:
# Как мы видим, в результате данного запроса, много юзеров совершило одинаковое количество заказов.
# Конкретно в нашем примере количество юзеров совершивших 17 покупок равно 7,
# но будь их например 10 возникли бы вопросы, как с этим  поступить.
select(sql)

   user_id  cnt_orders
0   733391          19
1   947386          18
2   809966          17
3   936288          17
4   798831          17
5   880616          17
6   975953          17
7   755529          16
8   746930          16
9   729093          16

In [67]:
# 2 шаг. Получив необходимый список юзеров, отберём их из основных данных с помощью INNER JOIN. 
# Перед этим поместим  список юзеров в представление  cte. 
sql = ''' 
WITH cte AS (SELECT 
                    user_id,
                    COUNT(DISTINCT id) AS cnt_orders
               FROM orders
              WHERE to_char(created_at, 'YYYY') = '2023'
              GROUP BY 1
              ORDER BY 2 DESC
              LIMIT 10)


SELECT  
       to_char(o.created_at, 'YYYY - MM') AS month,
       o.user_id, 
       AVG(o.total_price) AS avg_order_size
FROM orders o 
     INNER JOIN cte 
        ON o.user_id = cte.user_id
     WHERE to_char(o.created_at, 'YYYY-MM') = '2023-04'
GROUP BY 1, 2

            '''

In [68]:
select(sql)

       month  user_id  avg_order_size
0  2023 - 04   936288   519477.058824
1  2023 - 04   947386   582152.777778

In [69]:
# 3 шаг. Узнаем имя и email этих товарищей, присоединив таблицу users. 

sql = ''' 
WITH cte AS (SELECT 
                    user_id,
                    COUNT(DISTINCT id) AS cnt_orders
               FROM orders
              WHERE to_char(created_at, 'YYYY') = '2023'
              GROUP BY 1
              ORDER BY 2 DESC
              LIMIT 10)


SELECT  
       to_char(o.created_at, 'YYYY - MM') AS month,
       o.user_id,
       u.name,
       u.email,
       AVG(o.total_price) AS avg_order_size
FROM orders o 
     INNER JOIN cte 
        ON o.user_id = cte.user_id
     INNER JOIN  users u
        ON cte.user_id = u.id
     WHERE to_char(o.created_at, 'YYYY-MM') = '2023-04'
GROUP BY 1, 2, 3, 4

            '''

In [70]:
select(sql)

,month,user_id,name,email,avg_order_size
0,2023 - 04,936288,Robin Martinez,jeffrey63@example.org,519477.058824
1,2023 - 04,947386,Timothy Mitchell,aaronnelson@example.net,582152.777778

________________________________________________

In [71]:
# После использования соединения с базой данных через SQLAlchemy, 
# рекомендуется явно закрывать соединение, чтобы освободить ресурсы. 
conn.dispose()